### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by Zesky665** [humio/atom-elm-format#12]
[Enter steps to reproduce below:]
1. Install elm-format
2. Turn on format on save
3. Try to save file

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [elm-format](https://github.com/triforkse/atom-elm-format) package, v2.0.1
### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:262

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:374:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at Object.format (/home/zharkoc/.atom/packages/elm-format/lib/elm-format.js:101:5)
    at /home/zharkoc/.atom/packages/elm-format/lib/elm-format.js:49:25
    at Object.debounce (/home/zharkoc/.atom/packages/elm-format/lib/elm-format.js:57:7)
    at /home/zharkoc/.atom/packages/elm-format/lib/elm-format.js:48:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  5x -0:05.6.0 blur (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "html-tab",
      "ionide-fsharp",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "welcome",
      "markdown-writer"
    ]
  },
  "elm-format": {
    "binary": "/home/zharkoc/Desktop/Elm/elm-stuff/packages/elm-format"
  }
}
```
### Installed Packages

``` coffee
# User
elm-format, v2.0.1
language-elixir, v0.13.1
language-elm, v1.5.0
linter, v1.11.14
linter-elm-make, v0.13.2

# Dev
No dev packages
```

**Comment by benjick** [comment]
Is `elm-format` executable?

**Comment by vjtyagi** [comment]
Making it executable didn't help either

**Comment by anagrius** [comment]
Is this still relevant?

**Comment by benjick** [comment]
Closing due to inactivity
